apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # this must match plural+group below
  name: appmgrs.ericsson.com
spec:
  group: ericsson.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: appmgrs
    singular: appmgr
    kind: Deployment
    shortNames:
    - am
    categories:
    - all
  subresources:
    status: {}
